tech-soldier/e-commerce

README.md

test from dev branch

---

watches/database/migrations/2014_10_12_000000_create_users_table.php

aina - made a comment in migration table

---

README.md

just trying this again with new branch name

added line in readme

---

README.md

Milad testing

---

watches/resources/views/welcome.blade.php

Just adding a heading to site to test

adding a heading to test site on server

---

README.md

test working branch alexandr

---

watches/resources/views/homepage.blade.php

minor filename change to it can work on server

minor .jpg file name chnage

---

watches/database/migrations/2020_07_30_164840_create_watches_table.php
watches/database/migrations/2020_07_30_165750_create_admins_table.php
watches/database/migrations/2020_07_30_170441_create_customers_table.php
watches/database/migrations/2020_07_30_171314_create_categories_table.php
watches/database/migrations/2020_07_30_171519_create_transactions_table.php
watches/database/migrations/2020_07_30_171819_create_taxes_table.php
watches/database/migrations/2020_07_30_172214_create_orders_table.php
watches/database/migrations/2020_07_30_172543_create_order_watches_table.php

migration file -- watches primary table

aina-- just made the watches primary table migration file

---

watches/database/seeds/DatabaseSeeder.php
watches/database/seeds/SeedAdminsTable.php
watches/database/seeds/SeedCustomersTable.php
watches/database/seeds/SeedWatchesTable.php

finished another 5 records for the watches table - all female

aina -- finished another 5 records for the watches- all female this time

---

watches/app/Http/Controllers/PagesController.php
watches/public/css/styles.css
watches/resources/views/about.blade.php
watches/routes/web.php

updated the about page, added some lines, changed lineheight, margin top of text, margin bottom of div and removed the blue dots on the special featured area

Dawnbranch

---

watches/database/seeds/SeedWatchesTable.php

aina -- made changes to watches seeder file

---

watches/public/html/About.html
watches/public/html/Contact.html
watches/public/html/Homepage.html
watches/public/html/Shop.html
watches/public/html/product_detail.html

created html folder in public folder, added html templates

added html templates into htm folder in public

---

watches/resources/views/layouts/layout.blade.php

modified existing layout.blade.php please check it out make sure it looks right

modified existing layout.blade.php new new page layout

---

watches/resources/views/watchhome.blade.php

created new homepage with watchhome.blade.php

added new watchhome.blade.php for the homepage

---

watches/public/css/style.css
watches/resources/views/about.blade.php
watches/resources/views/contact.blade.php
watches/resources/views/detail.blade.php
watches/resources/views/shop.blade.php

fixed images on banners

---

watches/database/seeds/SeedWatchesTable.php
watches/resources/views/about.blade.php

rerun php artisan migrate:refresh --seed

one image as all image for testing

---

watches/app/Http/Controllers/WatchController.php
watches/app/Watch.php
watches/public/css/style.css
watches/resources/views/shop.blade.php
watches/routes/web.php

created shop dynamiclaly, watchescontroller and routes edited

created shop dynamiclaly, watchescontroller and routes edited

---

watches/app/Http/Controllers/WatchController.php
watches/resources/views/shop.blade.php

Made categories dynamic on shop page

Made categories dynamic on shop page

---

watches/app/Http/Controllers/WatchController.php
watches/database/migrations/2020_07_30_164840_create_watches_table.php
watches/database/seeds/SeedWatchesTable.php
watches/resources/views/detail.blade.php
watches/resources/views/shop.blade.php
watches/routes/web.php

fixed the watch_id situation, everyone needs to do migrate refresh seed

fixed the watch_id situation, everyone needs to do migrate refresh seed

---

watches/resources/views/detail.blade.php

fixed image path

---

watches/resources/views/shop.blade.php

fixed shop colum width per individual item and made categories dynamic

fixed shop colum width per individual item and made categories dynamic

---

watches/database/seeds/SeedWatchesTable.php

aina -- added aakashs seeder for watches

---

watches/resources/views/detail.blade.php

all watch specs are now on page

all watch specs are now on page

---

README.md
watches/database/seeds/SeedWatchesTable.php

Aakashdevelopment

---

watches/public/css/style.css
watches/resources/views/cart.blade.php
watches/resources/views/detail.blade.php
watches/resources/views/shop.blade.php
watches/resources/views/watchhome.blade.php

Milad branch

---

watches/database/migrations/2020_07_30_172214_create_orders_table.php

fixed conflict

---

watches/routes/web.php

correcting error

---

watches/resources/views/auth/login.blade.php
watches/resources/views/auth/passwords/confirm.blade.php
watches/resources/views/auth/passwords/email.blade.php
watches/resources/views/auth/passwords/reset.blade.php
watches/resources/views/auth/register.blade.php
watches/resources/views/auth/verify.blade.php
watches/resources/views/partials/nav.blade.php

fixed top menu a bit, i can finalize it once we can loging as users

fixed top menu a bit, i can finalize it once we can loging as users

---

watches/public/css/style.css
watches/resources/views/detail.blade.php
watches/resources/views/partials/nav.blade.php

made detail page adjustments (css) and also made it responsive

made detail page adjustments (css) and also made it responsive

---

watches/public/css/style.css
watches/resources/views/home.blade.php
watches/resources/views/partials/nav.blade.php

fixed top menu to show correct options to guests users and admins

fixed top menu to show correct options to guests users and admins

---

watches/routes/web.php

clean up routes (unused) for edit_watches

clean up routes for edit_watch

---

watches/routes/web.php

added delete route in web.php

---

watches/resources/views/partials/nav.blade.php
watches/resources/views/shop.blade.php

search on nav

---

watches/resources/views/partials/nav.blade.php

Search on left side

---

watches/resources/views/partials/nav.blade.php

change again in search position

---

watches/routes/web.php

Just removed an extra route for edit user from web.php

removed extra edit user route from web.php

---

watches/resources/views/partials/header.blade.php

fixed favicon

---

watches/app/Http/Controllers/CheckoutController.php
watches/resources/views/checkout.blade.php

tested and slightly editted card validation

tested and slightly editted card validation

---

watches/database/migrations/2020_07_30_172543_create_order_watch_table.php
watches/database/seeds/DatabaseSeeder.php
watches/database/seeds/SeedOrderWatchTable.php

changed the intesect table name to order_watch instead of order_watches for convention purposes

aina -- due to naming conventions, changed order_watches to order_watch

---

watches/routes/web.php

Auth and Admin both middle wares applied to admin website

both middlewares auth and admin applied to admin website

---

watches/public/css/style.css
watches/resources/views/admin/categories_table.blade.php

updated image on contact page, changed created at and updtated at to read created on and updated on to match other tables on admin

updated picture on contact page to a winnipeg map

---

watches/resources/views/shop_search.blade.php

search changes

---

watches/resources/views/layouts/layout.blade.php
watches/resources/views/partials/footer.blade.php

flash message slides up

---

watches/composer.lock
watches/public/css/style.css
watches/resources/views/auth/login.blade.php
watches/resources/views/partials/footer.blade.php

change in login image

---

watches/public/css/style.css
watches/resources/views/auth/register.blade.php

Register page images modified

---

watches/resources/views/about.blade.php

about page

---

watches/app/Http/Controllers/WatchController.php

Added an authenticated user to shop page (profile photo was missing)

authenticated user added to watch controller index method
